ElifERAT GRUP13
nozgulcelebi/IST480 pull request #50
Opened 2023-06-15 19:55 UTC by eliferat

2023-06-15 19:58 UTC, eliferat commented
İST480-FİNAL GRUP 13

2023-06-18 07:47 UTC, nozgulcelebi requested changes
Elif merhaba, 
Dosyalarını hem grup-13 altına hem de main branche eklemişsin. Sistemini kontrol et, dosyaların sadece grup-13 altında olmalıdır.

2023-06-18 11:30 UTC, eliferat commented
Hocam merhaba ilk önce yanlış yapmışız silmek için uğraştık ancak sanırım bizim silmek için iznimiz yok main branchtekileri o yüzden silemedik grup 13 içerisinde de dosyalarımızın göründüğünü söylemiştiniz konuştuğumuzda bu durumda ne yapmamız gerekiyor. İlginiz için teşekkür ederim. Elif ERAT Nilgün ÖZGÜL ÇELEBİ ***@***.***> şunları yazdı (18 Haz 2023 10:47):﻿
@nozgulcelebi requested changes on this pull request.

Elif merhaba,
Dosyalarını hem grup-13 altına hem de main branche eklemişsin. Sistemini kontrol et, dosyaların sadece grup-13 altında olmalıdır.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-19 17:35 UTC, nozgulcelebi approved these changes

2023-06-19 17:35 UTC, merged